name: sdui_craftd_getx
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  cupertino_icons: ^1.0.6
  # mobx: ^2.3.3+2
  # flutter_mobx: ^2.0.6+1
  # mobx_codegen: ^2.0.7
  material: ^1.0.0+2
  # dio: ^5.4.1
  # equatable: ^2.0.5
  craftd_widget: ^1.0.1
  get: ^4.6.6
  # Comentar esse trecho para rodar o app e descomentar para alterar/adicionar alguma entidade
  # objectbox: ^4.0.3 # A principio usado so para buildar a primeira vez
  # Esse nao comentar
  objectbox_flutter_libs: any
  # Comentar esse trecho para rodar o app e descomentar para alterar/adicionar alguma entidade
  # objectbox_sync_flutter_libs: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.01
  # Comentar esse trecho para rodar o app e descomentar para alterar/adicionar alguma entidade
  # build_runner: ^2.4.9
  # objectbox_generator: any

# Comentar esse trecho para rodar o app e descomentar para alterar/adicionar alguma entidade
# objectbox:
#   output_dir: database
# #   output_dir: flutter pub run build_runner build

flutter:
  uses-material-design: true

  assets:
    - assets/dynamic.json
